name: Send Daily Email from Dify (Single Job)

on:
  schedule:
    # 每天的 UTC 时间 8 点运行 (对应北京时间下午 4 点)
    - cron: '0 8 * * *'
  
  # 允许在 Actions 页面手动触发此工作流，方便测试
  workflow_dispatch:

jobs:
  fetch_and_send_email:
    runs-on: ubuntu-latest
    name: Fetch Dify Content and Send Email

    steps:
      # 步骤 1: 从 Dify 获取邮件的 HTML 内容
      - name: "Step 1: Fetch Content from Dify"
        # 为这个步骤设置一个ID，以便下一步可以引用它的输出
        id: fetch_dify
        run: |
          # 调用 Dify 工作流 API
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")

          # 打印原始返回，方便调试
          echo "--- Raw Response from Dify ---"
          echo "$API_RESPONSE"
          echo "------------------------------"

          # 验证返回的是否为有效的JSON
          if ! echo "$API_RESPONSE" | jq . > /dev/null 2>&1; then
            echo "::error::Failed to parse JSON response from Dify. Check API Key or Dify status."
            exit 1
          fi

          # 解析出 html_content 字段
          HTML=$(echo "$API_RESPONSE" | jq -r '.data.outputs.html_content')

          # 检查内容是否为空
          if [ -z "$HTML" ]; then
            echo "::error::Dify API did not return content from the 'html_content' field."
            exit 1
          fi

          # 将HTML内容设置为此步骤的输出变量，供下一步使用
          echo "html_content<<EOF" >> $GITHUB_OUTPUT
          echo "$HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 步骤 2: 使用上一步获取的内容发送邮件
      - name: "Step 2: Send Email via Port 587"
        uses: dawidd6/action-send-mail@v3
        with:
          # 使用我们验证过的可靠配置
          server_address: smtp.qq.com
          server_port: 587
          
          # 您的邮箱凭证 (从Secrets读取)
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          # 邮件信息
          subject: '每日简报 - 由 Dify 生成'
          to: ${{ secrets.MAIL_TO }}
          from: Dify 每日简报 <${{ secrets.MAIL_USERNAME }}>
          
          # 关键步骤：引用上一步(id: fetch_dify)的输出(html_content)作为邮件正文
          html_body: ${{ steps.fetch_dify.outputs.html_content }}
