# .github/workflows/send-daily-email.yml

name: Test Email Sending with QQ Mail

on:
  # 允许在 Actions 页面手动触发此工作流，方便测试
  workflow_dispatch:

jobs:
  test_send_email:
    runs-on: ubuntu-latest
    name: Send a Test Email using QQ Mail SMTP

    steps:
      # 步骤 1: 发送测试邮件
      - name: Send test email action
        uses: dawidd6/action-send-mail@v3
        with:
          # --- QQ 邮箱服务器配置 ---
          # 注意：这里已修改为 QQ 邮箱的 SMTP 服务器地址
          server_address: smtp.qq.com
          # QQ 邮箱要求使用 SSL 加密的 465 端口
          server_port: 465
          # 必须启用 SSL
          secure: true

          # --- 您的 QQ 邮箱凭据 (从 GitHub Secrets 读取) ---
          # 您的 QQ 邮箱地址 (例如: 12345@qq.com)
          username: ${{ secrets.MAIL_USERNAME }}
          # 重要：这里不是您的 QQ 登录密码，而是需要在 QQ 邮箱设置中生成的 "授权码"
          password: ${{ secrets.MAIL_PASSWORD }}

          # --- 邮件信息 ---
          subject: 'GitHub Actions 邮件发送测试'
          # 收件人邮箱，从 Secrets 中读取
          to: ${{ secrets.MAIL_TO }}
          # 发件人邮箱，这里也应该是您的 QQ 邮箱地址
          from: ${{ secrets.MAIL_FROM }}
          
          # 使用一个简单的 HTML 内容进行测试
          html_body: |
            <h1>✅ 测试邮件</h1>
            <p>你好,</p>
            <p>这封邮件由 GitHub Actions 自动发出。</p>
            <p>如果你收到了这封邮件，说明你的 SMTP 配置和 GitHub Secrets 设置都是正确的！</p>
            <p>接下来你就可以把 Dify 的逻辑整合回来了。</p>
