# .github/workflows/send-daily-email.yml

name: Send Daily Email from Dify

on:
  schedule:
    # 每天的 UTC 时间上午 8 点运行 (对应北京时间下午 4 点)
    - cron: '0 8 * * *'
  
  # 允许您手动在 Actions 页面点击按钮来测试运行
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Fetch Dify Content and Send Email

    steps:
      # 步骤 1: (新增) 从 Dify 获取邮件的 HTML 内容
      - name: "Step 1: Fetch Content from Dify"
        # 为这个步骤设置一个ID，以便下一步可以引用它的输出
        id: fetch_dify
        run: |
          # 调用 Dify 工作流 API
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")

          # 验证返回的是否为有效的JSON
          if ! echo "$API_RESPONSE" | jq . > /dev/null 2>&1; then
            echo "::error::Failed to parse JSON response from Dify. Check API Key or Dify status."
            exit 1
          fi

          # 解析出 html_content 字段
          HTML=$(echo "$API_RESPONSE" | jq -r '.data.outputs.html_content')

          # 检查内容是否为空
          if [ -z "$HTML" ]; then
            echo "::error::Dify API did not return content from the 'html_content' field."
            exit 1
          fi

          # 将HTML内容设置为此步骤的输出变量，供下一步使用
          echo "html_content<<EOF" >> $GITHUB_OUTPUT
          echo "$HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 步骤 2: (修正) 使用上一步获取的内容发送邮件
      - name: "Step 2: Send Email with Dify Content"
        uses: dawidd6/action-send-mail@v3
        with:
          # 必需: 修正为我们测试通过的邮件服务器地址
          server_address:  1.202.161.134
          
          # 必需: 修正为我们测试通过的邮件服务器端口
          server_port: 587

          # 必需: 用来发邮件的邮箱账号 (从Secrets读取)
          username: ${{ secrets.MAIL_USERNAME }}

          # 必需: 邮箱授权码 (从Secrets读取)
          password: ${{ secrets.MAIL_PASSWORD }}

          # 必需: 邮件主题
          subject: '每日简报 - 由 Dify 生成'

          # 必需: 收件人邮箱 (建议使用Secret管理)
          to: ${{ secrets.MAIL_TO }}

          # 推荐: 添加发件人名称，使邮件更规范
          from: Dify 每日简报 <${{ secrets.MAIL_USERNAME }}>
          
          # 关键修正: 使用上一步的输出作为HTML正文
          # 注意这里用的是 html_body 而不是 body
          html_body: ${{ steps.fetch_dify.outputs.html_content }}
