name: 每日邮件报告

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  send-daily-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: 调用Dify获取数据
      id: get-data
      run: |
        curl -X POST "https://dify.comlan.com/v1/workflows/run" \
          -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"inputs": {}, "response_mode": "blocking", "user": "github-actions"}' \
          -o response.json
        
        # 提取HTML内容
        if jq -e '.data.outputs.email_html' response.json > /dev/null 2>&1; then
          jq -r '.data.outputs.email_html' response.json > email_content.html
          echo "content_type=html" >> $GITHUB_OUTPUT
        else
          cat response.json > email_content.html
          echo "content_type=json" >> $GITHUB_OUTPUT
        fi
        
        echo "email_content<<EOF" >> $GITHUB_OUTPUT
        cat email_content.html >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: 发送邮件
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: mail.comlan.com
        server_port: 25
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: '每日报告 - $(date +"%Y-%m-%d")'
        body: ${{ steps.get-data.outputs.email_content }}
        to: wang.tianyang@comlan.com
        from: ai.public@comlan.com
        content_type: 'text/html'
