name: Send Daily Email from Dify (Timeout Fix)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Fetch from Dify and Send Email
    timeout-minutes: 10  # 整个任务10分钟超时

    steps:
      - name: Fetch and Parse Email Content from Dify
        id: dify_content
        run: |
          echo "开始调用Dify API..."
          
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")
          
          if [ -z "$API_RESPONSE" ]; then
            echo "::error::Dify API返回空响应"
            exit 1
          fi
          
          EMAIL_HTML=$(echo "$API_RESPONSE" | jq -r '.data.outputs.email_html // empty')
          
          if [ -z "$EMAIL_HTML" ]; then
            echo "::warning::使用备用内容"
            EMAIL_HTML="<html><body><h1>每日AI新闻摘要</h1><p>抱歉，今日内容获取失败，请稍后重试。</p></body></html>"
          fi
          
          echo "email_html<<EOF" >> $GITHUB_OUTPUT
          echo "$EMAIL_HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Test Network Connection
        run: |
          echo "测试网络连接..."
          ping -c 3 mail.comlan.com || echo "ping失败"
          telnet mail.comlan.com 25 || echo "端口25连接失败"

      - name: Send email with timeout
        run: |
          echo "开始发送邮件..."
          timeout 300 node -e "
            const nodemailer = require('nodemailer');
            
            const transporter = nodemailer.createTransporter({
              host: 'mail.comlan.com',
              port: 25,
              secure: false,
              auth: {
                user: process.env.MAIL_USERNAME,
                pass: process.env.MAIL_PASSWORD
              },
              connectionTimeout: 30000,
              greetingTimeout: 30000,
              socketTimeout: 30000
            });
            
            const mailOptions = {
              from: process.env.MAIL_USERNAME,
              to: 'wang.tantyang@comlan.com',
              subject: '来自 Dify 的每日报告',
              html: process.env.EMAIL_HTML
            };
            
            transporter.sendMail(mailOptions, (error, info) => {
              if (error) {
                console.error('发送失败:', error);
                process.exit(1);
              } else {
                console.log('发送成功:', info.messageId);
                process.exit(0);
              }
            });
          "
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          EMAIL_HTML: ${{ steps.dify_content.outputs.email_html }}
