# .github/workflows/send-daily-email.yml

name: Send Daily Email from Dify

on:
  schedule:
    # 每天的 UTC 时间上午 8 点运行 (北京时间下午 4 点)
    - cron: '0 8 * * *'
  
  # 允许在 Actions 页面手动触发此工作流，方便测试
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Fetch from Dify and Send Email

    steps:
      # 步骤 1: 调用 Dify API 并使用 jq 解析返回的 JSON
      - name: Fetch and Parse Email Content from Dify
        id: dify_content
        run: |
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")

          # 检查 API 响应是否为空
          if [ -z "$API_RESPONSE" ]; then
            echo "::error::Dify API returned an empty response."
            exit 1
          fi
          
          # 使用 jq 解析 JSON 并将结果设置为此步骤的输出变量
          # 根据你提供的数据，Dify 返回的业务数据不在 'data' 字段下，而是直接在顶层
          EMAIL_SUBJECT=$(echo "$API_RESPONSE" | jq -r '.subject // "Dify 每日报告"')
          EMAIL_HTML=$(echo "$API_RESPONSE" | jq -r '.email_html // "无法从 Dify 获取邮件内容。"')
          
          # 将解析出的内容设置为 GitHub Actions 的输出变量
          echo "email_subject<<EOF" >> $GITHUB_OUTPUT
          echo "$EMAIL_SUBJECT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "email_html<<EOF" >> $GITHUB_OUTPUT
          echo "$EMAIL_HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 步骤 2: 使用上一步解析出的内容发送邮件
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          # 邮件服务器配置
          server_address: mail.comlan.com
          server_port: 25
          secure: false
          
          # 认证信息
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          # 邮件内容 - 完全来自于上一步解析的结果
          subject: ${{ steps.dify_content.outputs.email_subject }}
          html_body: ${{ steps.dify_content.outputs.email_html }}
          
          # 收件人
          to: wang.tianyang@comlan.com
          
          # 发件人
          from: ${{ secrets.MAIL_USERNAME }}
