# .github/workflows/send-daily-email.yml

name: Send Daily Email from Dify

on:
  schedule:
    # 每天的 UTC 时间上午 8 点运行 (北京时间下午 4 点)
    - cron: '0 8 * * *'
  
  # 允许在 Actions 页面手动触发此工作流，方便测试
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Fetch from Dify and Send Email

    steps:
      # 步骤 1: 直接调用 Dify Workflow API 获取原始的 HTML 响应
      - name: Fetch raw email body from Dify
        id: dify_content
        run: |
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run") # <--- 已为你替换成你的 Dify API URL

          # 检查 API 响应是否为空
          if [ -z "$API_RESPONSE" ]; then
            echo "::error::Dify API returned an empty response."
            exit 1
          fi

          # 将从 Dify 获取到的全部原始响应内容设置为输出变量
          echo "email_body<<EOF" >> $GITHUB_OUTPUT
          echo "$API_RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 步骤 2: 使用上一步从 Dify 获取的全部内容作为邮件正文来发送邮件
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          # 邮件服务器配置
          server_address: mail.comlan.com
          server_port: 25
          secure: false
          
          # 认证信息
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          # 邮件内容
          subject: '来自 Dify 的每日报告'
          html_body: ${{ steps.dify_content.outputs.email_body }}
          
          # 收件人
          to: wang.tianyang@comlan.com
          
          # 发件人
          from: ${{ secrets.MAIL_USERNAME }}
