- name: Send email action
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: mail.comlan.com
    server_port: 25
    username: ${{ secrets.MAIL_USERNAME }}
    password: ${{ secrets.MAIL_PASSWORD }}
    subject: '每日报告 - ${{ github.workflow }}'
    body: |
      你好,
      这是一封来自 GitHub Actions 的自动邮件。
      今天是 {{ date }}.
      祝好!
    to: wang.tianyang@comlan.com
    from: ai.public@comlan.com
