name: Send Daily Email from Dify (Auth Debug Version)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Fetch from Dify and Send Email

    steps:
      - name: Fetch and Parse Email Content from Dify
        id: dify_content
        run: |
          echo "开始调用Dify API..."
          
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")
          
          if [ -z "$API_RESPONSE" ]; then
            echo "::error::Dify API返回空响应"
            exit 1
          fi
          
          EMAIL_HTML=$(echo "$API_RESPONSE" | jq -r '.data.outputs.email_html // empty')
          
          if [ -z "$EMAIL_HTML" ]; then
            echo "::warning::使用备用内容"
            EMAIL_HTML="<html><body><h1>每日AI新闻摘要</h1><p>抱歉，今日内容获取失败，请稍后重试。</p></body></html>"
          fi
          
          echo "email_html<<EOF" >> $GITHUB_OUTPUT
          echo "$EMAIL_HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Test Email Authentication (Port 25)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.comlan.com
          server_port: 25
          secure: false
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "测试邮件 - 端口25"
          html_body: "<html><body><h1>测试邮件</h1><p>这是端口25的测试邮件</p></body></html>"
          to: wang.tantyang@comlan.com
          from: ${{ secrets.MAIL_USERNAME }}
          nodemailerlog: true
          nodemailerdebug: true

      - name: Test Email Authentication (Port 587)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.comlan.com
          server_port: 587
          secure: false
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "测试邮件 - 端口587"
          html_body: "<html><body><h1>测试邮件</h1><p>这是端口587的测试邮件</p></body></html>"
          to: wang.tantyang@comlan.com
          from: ${{ secrets.MAIL_USERNAME }}
          nodemailerlog: true
          nodemailerdebug: true

      - name: Test Email Authentication (Port 465)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.comlan.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "测试邮件 - 端口465"
          html_body: "<html><body><h1>测试邮件</h1><p>这是端口465的测试邮件</p></body></html>"
          to: wang.tantyang@comlan.com
          from: ${{ secrets.MAIL_USERNAME }}
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Final Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.comlan.com
          server_port: 25
          secure: false
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "来自 Dify 的每日报告"
          html_body: ${{ steps.dify_content.outputs.email_html }}
          to: wang.tantyang@comlan.com
          from: ${{ secrets.MAIL_USERNAME }}
          nodemailerlog: true
          nodemailerdebug: true
