# .github/workflows/send-daily-email.yml

name: Send Daily Email from Dify (Final Version)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Fetch from Dify and Send Email

    steps:
      # 步骤 1: 调用 Dify API 并解析返回的 JSON (包含调试输出)
      - name: Fetch and Parse Email Content from Dify
        id: dify_content
        run: |
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")

          # --- 关键调试代码：打印出 Dify 返回的原始数据 ---
          echo "Dify Raw Response:"
          echo "$API_RESPONSE"
          # ------------------------------------------------

          # 检查 API 响应是否为空
          if [ -z "$API_RESPONSE" ]; then
            echo "::error::Dify API returned an empty response."
            exit 1
          fi
          
          # 使用 jq 解析 JSON，并提取 'email_html' 字段
          EMAIL_HTML=$(echo "$API_RESPONSE" | jq -r '.email_html // "无法从 Dify 获取邮件内容。"')
          
          # 将解析出的内容设置为 GitHub Actions 的输出变量
          echo "email_html<<EOF" >> $GITHUB_OUTPUT
          echo "$EMAIL_HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 步骤 2: 使用上一步解析出的内容发送邮件
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          # 邮件服务器配置 - 已修正为行业标准的加密端口
          server_address: mail.comlan.com
          server_port: 465
          secure: true
          
          # 认证信息
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          # 邮件内容
          subject: "来自 Dify 的每日报告"
          html_body: ${{ steps.dify_content.outputs.email_html }}
          
          # 收件人
          to: wang.tantyang@comlan.com
          
          # 发件人
          from: ${{ secrets.MAIL_USERNAME }}
