name: Send Daily Email from Dify (Simple Version)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Fetch from Dify and Send Email
    timeout-minutes: 5

    steps:
      - name: Fetch and Parse Email Content from Dify
        id: dify_content
        run: |
          echo "开始调用Dify API..."
          
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")
          
          if [ -z "$API_RESPONSE" ]; then
            echo "::error::Dify API返回空响应"
            exit 1
          fi
          
          EMAIL_HTML=$(echo "$API_RESPONSE" | jq -r '.data.outputs.email_html // empty')
          
          if [ -z "$EMAIL_HTML" ]; then
            echo "::warning::使用备用内容"
            EMAIL_HTML="<html><body><h1>每日AI新闻摘要</h1><p>抱歉，今日内容获取失败，请稍后重试。</p></body></html>"
          fi
          
          echo "email_html<<EOF" >> $GITHUB_OUTPUT
          echo "$EMAIL_HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email using curl
        run: |
          echo "使用curl发送邮件..."
          
          # 创建邮件文件
          cat > email.txt << 'EOF'
          From: ${{ secrets.MAIL_USERNAME }}
          To: wang.tantyang@comlan.com
          Subject: 来自 Dify 的每日报告
          Content-Type: text/html; charset=UTF-8
          
          ${{ steps.dify_content.outputs.email_html }}
          EOF
          
          # 使用curl发送邮件
          timeout 60 curl -v \
            --url smtp://mail.comlan.com:25 \
            --mail-from "${{ secrets.MAIL_USERNAME }}" \
            --mail-rcpt "wang.tantyang@comlan.com" \
            --upload-file email.txt \
            --user "${{ secrets.MAIL_USERNAME }}:${{ secrets.MAIL_PASSWORD }}"
