name: Send Daily Email from Dify (Python Version)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Fetch from Dify and Send Email
    timeout-minutes: 5

    steps:
      - name: Fetch and Parse Email Content from Dify
        id: dify_content
        run: |
          echo "开始调用Dify API..."
          
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")
          
          if [ -z "$API_RESPONSE" ]; then
            echo "::error::Dify API返回空响应"
            exit 1
          fi
          
          EMAIL_HTML=$(echo "$API_RESPONSE" | jq -r '.data.outputs.email_html // empty')
          
          if [ -z "$EMAIL_HTML" ]; then
            echo "::warning::使用备用内容"
            EMAIL_HTML="<html><body><h1>每日AI新闻摘要</h1><p>抱歉，今日内容获取失败，请稍后重试。</p></body></html>"
          fi
          
          echo "email_html<<EOF" >> $GITHUB_OUTPUT
          echo "$EMAIL_HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email using Python
        run: |
          echo "使用Python发送邮件..."
          
          # 创建Python脚本
          cat > send_email.py << 'EOF'
          import smtplib
          import ssl
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart
          import os
          import sys
          
          def send_email():
              try:
                  # 邮件配置
                  smtp_server = "mail.comlan.com"
                  smtp_port = 25
                  username = os.environ['MAIL_USERNAME']
                  password = os.environ['MAIL_PASSWORD']
                  from_email = os.environ['MAIL_USERNAME']
                  to_email = "wang.tantyang@comlan.com"
                  
                  # 创建邮件
                  msg = MIMEMultipart('alternative')
                  msg['From'] = from_email
                  msg['To'] = to_email
                  msg['Subject'] = "来自 Dify 的每日报告"
                  
                  # 添加HTML内容
                  html_content = os.environ['EMAIL_HTML']
                  html_part = MIMEText(html_content, 'html', 'utf-8')
                  msg.attach(html_part)
                  
                  # 发送邮件
                  print(f"连接到 {smtp_server}:{smtp_port}")
                  server = smtplib.SMTP(smtp_server, smtp_port)
                  server.set_debuglevel(1)  # 启用调试
                  
                  print("开始认证...")
                  server.login(username, password)
                  
                  print("发送邮件...")
                  server.sendmail(from_email, to_email, msg.as_string())
                  server.quit()
                  
                  print("邮件发送成功！")
                  return True
                  
              except Exception as e:
                  print(f"发送失败: {e}")
                  return False
          
          if __name__ == "__main__":
              success = send_email()
              sys.exit(0 if success else 1)
          EOF
          
          # 运行Python脚本
          timeout 60 python3 send_email.py
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          EMAIL_HTML: ${{ steps.dify_content.outputs.email_html }}
