# .github/workflows/send-daily-email.yml

name: Send Daily Email

on:
  schedule:
    # 每天的 UTC 时间上午 8 点运行 (可以换算成你的时区)
    # Cron 语法: 分 时 日 月 周
    # '0 8 * * *' 表示每天的 8:00
    - cron: '0 8 * * *'
  
  # 这个 workflow_dispatch 允许你手动在 Actions 页面点击按钮来测试运行
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Send a daily report email

    steps:
      - name: Send email action
        uses: dawidd6/action-send-mail@v3
        with:
          # 必需: 你的邮件服务器地址. 
          # 例如，QQ邮箱是 smtp.qq.com, Gmail是 smtp.gmail.com
          server_address: mail.comlan.com
          
          # 必需: 你的邮件服务器端口.
          # 通常是 465 (SSL) 或 587 (TLS).
          server_port: 25

          # 必需: 你用来发邮件的邮箱账号
          username: ${{ secrets.MAIL_USERNAME }}

          # 必需: 你的邮箱密码或应用专用密码 (非常重要!)
          password: ${{ secrets.MAIL_PASSWORD }}

          # 必需: 邮件主题
          subject: '每日报告 - ${{ github.workflow }}'

          # 必需: 邮件正文. 你可以使用 HTML.
          # 你也可以用 from_file: 来读取文件内容作为正文
          body: |
            你好,

            这是一封来自 GitHub Actions 的自动邮件。
            今天是 {{ date }}.

            祝好!

          # 必需: 收件人邮箱 (可以有多个，用逗号隔开)
          to: wang.tianyang@comlan.com

          # 可选: 发件人邮箱
          from: ai.public@comlan.com

          # 可选: 抄送 (CC)
          # cc: user3@example.com,user4@example.com

          # 可选: 密送 (BCC)
          # bcc: user5@example.com
