name: Send Daily Email from Dify (Correct Version)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send_email_job:
    runs-on: ubuntu-latest
    name: Send a daily report email

    steps:
      - name: Fetch and Parse Email Content from Dify
        id: dify_content
        run: |
          echo "开始调用Dify API..."
          
          API_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "inputs": {},
                  "response_mode": "blocking",
                  "user": "github-action-runner"
                }' \
            "https://dify.comlan.com/v1/workflows/run")
          
          if [ -z "$API_RESPONSE" ]; then
            echo "::error::Dify API返回空响应"
            exit 1
          fi
          
          EMAIL_HTML=$(echo "$API_RESPONSE" | jq -r '.data.outputs.email_html // empty')
          
          if [ -z "$EMAIL_HTML" ]; then
            echo "::warning::使用备用内容"
            EMAIL_HTML="<html><body><h1>每日AI新闻摘要</h1><p>抱歉，今日内容获取失败，请稍后重试。</p></body></html>"
          fi
          
          echo "email_html<<EOF" >> $GITHUB_OUTPUT
          echo "$EMAIL_HTML" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email with Dify content
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.comlan.com
          server_port: 25
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "来自 Dify 的每日报告"
          body: ${{ steps.dify_content.outputs.email_html }}
          to: wang.tianyang@comlan.com
          from: ai.public@comlan.com
